# Generated by Django 5.1.3 on 2024-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('email_add', models.CharField(max_length=40)),
            ],
        ),
    ]
